rabbitmq:
  orderTakingQueue: OrderTakingQueue
  orderNotificationExchange: OrderNotificationExchange
  orderNotificationQueue: OrderNotificationQueue
  orderNotificationRoutingKey: OrderNotificationRoutingKey
  host: localhost
  username: guest
  password: guest

spring:
  datasource:
    password: admin123
    url: jdbc:mysql://localhost:3306/ordersystem
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
